modules:

  enable::
    - tcl

  tcl:
    verbose: True
    hash_length: 0
    blacklist:
      - '%gcc'
      - '%intel'
      - '%clang'
      - '%nvhpc'
      - '%pgi'
    projections:
      all: '{name}/{version}'
    all:
      autoload: 'all'
      load_only_generated: true
    gcc:
      environment:
        set:
          MPICC_CC: 'gcc'
          MPICXX_CXX: 'g++'
          MPIF90_F90: 'gfortran'
    intel-parallel-studio:
      environment:
        set:
          MPICC_CC: 'icc'
          MPICXX_CXX: 'icpc'
          MPIF90_F90: 'ifort'
    intel:
      environment:
        set:
          MPICC_CC: 'icc'
          MPICXX_CXX: 'icpc'
          MPIF90_F90: 'ifort'
    pgi:
      environment:
        set:
          MPICC_CC: 'pgcc'
          MPICXX_CXX: 'pgc++'
          MPIF90_F90: 'pgfortran'
    llvm:
      environment:
        set:
          MPICC_CC: 'clang'
          MPICXX_CXX: 'clang++'
          MPIF90_F90: 'gfortran'
    nvhpc:
      environment:
        set:
          MPICC_CC: 'nvc'
          MPICXX_CXX: 'nvc++'
          MPIF90_F90: 'nvfortran'
