stages:
  - test

default:
  tags: [bb5_map]  # Will use a special deployment user with write permissions to `bsd`
  timeout: 3 day   # Building takes a while

# This is a blatant copy of the documentation deployment setup from `nse/ci`
# FIXME purge this once the move to GitLab is complete
.spack_setup_gerrit_ssh:
  - SSH_CONFIG=$HOME/.ssh/config
  - SSH_KEY=$HOME/.ssh/key
  - if [[ -f $SSH_CONFIG ]]; then echo "SSH config file $SSH_CONFIG already exists, exiting"; exit 1; fi
  - if [[ -z $BBPCIHPCDEPLOY_GERRIT_PRIVATE_KEY ]]; then echo 'Please set the $BBPCIHPCDEPLOY_GERRIT_PRIVATE_KEY variable'; exit 1; fi
  - |
    mkdir -p $(dirname $SSH_CONFIG) && 
    cp $BBPCIHPCDEPLOY_GERRIT_PRIVATE_KEY $SSH_KEY
    cat > $SSH_CONFIG <<EOF
    User $(whoami)
    IdentityFile ${SSH_KEY}
    StrictHostKeyChecking no
    IdentitiesOnly yes
    EOF
  - chmod 600 $SSH_CONFIG $SSH_KEY

.spack_basic_job:
  variables:
    # Max out duration to install stuff
    bb5_duration: "24:00:00"
    # We will do this ourselves, will be on GPFS
    GIT_STRATEGY: none
  before_script:
    # Tell Git how to re-write BBP GitLab URLs to use a token instead of SSH
    - export XDG_CONFIG_HOME=${PWD}/local_config
    - mkdir -p "${XDG_CONFIG_HOME}/git"
    - echo -e "[url \"https://gitlab-ci-token:${CI_JOB_TOKEN}@bbpgitlab.epfl.ch/\"]\n  insteadOf = git@bbpgitlab.epfl.ch:" > "${XDG_CONFIG_HOME}/git/config"
    - cat "${XDG_CONFIG_HOME}/git/config"

clone:
  extends: .spack_basic_job
  stage: test
  before_script:
    - !reference [.spack_setup_gerrit_ssh]
  script:
    - cat $HOME/.ssh/config
    - git clone -v --branch 2.5.6 --single-branch --depth 1 ssh://bbpcode.epfl.ch/sim/reportinglib/bbp
