spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - circuit-analysis
        - connectome-tools
        - emsim
        - gene-expression-volume
        - psp-validation
        - py-atlas-building-tools
        - py-bbp-analysis-framework
        - py-bbp-workflow
        - py-bluepy
        - py-bluepysnap
        - py-currentscape
        - py-entity-management
        - py-minis-validation
        - py-morphio
        - py-morphology-repair-workflow
        - py-simwriter
        - py-sonata-network-reduction
        - regiodesics
  packages:
    all:
      compiler: [gcc@9.3.0, intel]
      providers:
        mpi: [hpe-mpi@2.21]
        lapack: [intel-mkl@2019.3.199]
    hdf5:
      variants: ~mpi+hl
    highfive:
      variants: ~mpi
    libsonata:
      variants: ~mpi
    mvdtool:
      variants: ~mpi
    netcdf-c:
      variants: ~mpi
    py-h5py:
      variants: ~mpi
    py-mvdtool:
      variants: ~mpi
    python:
      version: [3.8.3]
    vtk:
      variants: ~mpi~ffmpeg~opengl2
  specs:
    - connectome-tools
    - emsim
    - gene-expression-volume
    - psp-validation%gcc ^neuron%intel
    - py-atlas-building-tools
    - py-bbp-analysis-framework
    - py-bbp-workflow ^py-h5py~mpi
    - py-bluepy
    - py-bluepysnap
    - py-currentscape
    - py-entity-management
    - py-minis-validation%gcc ^neuron%intel
    - py-morphio
    - py-morphology-repair-workflow
    - py-morph-tool%gcc ^neuron%intel
    - py-morph-tool@2.8.0%gcc ^neuron%intel
    - py-simwriter
    - py-sonata-network-reduction%gcc ^neuron%intel^py-ipython%gcc
    - regiodesics
