spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - brainbuilder
        - circuit-build
        - placement-algorithm
        - py-region-grower
  packages:
    all:
      compiler: [gcc@9.3.0, intel]
      providers:
        mpi: [hpe-mpi@2.21]
        lapack: [intel-mkl@2019.3.199]
    hdf5:
      variants: ~mpi+hl
    highfive:
      variants: ~mpi
    libsonata:
      variants: ~mpi
    mvdtool:
      variants: ~mpi
    netcdf-c:
      variants: ~mpi
    py-h5py:
      variants: ~mpi
    py-mvdtool:
      variants: ~mpi
    python:
      version: [3.8.3]
    vtk:
      variants: ~mpi~ffmpeg~opengl2
  specs:
    - brainbuilder
    - circuit-build
    - placement-algorithm
    - placement-algorithm@2.1.4
    - py-region-grower
    - py-region-grower@0.2.4
