spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - asciitoh5
        - functionalizer
        - model-neocortex
        - nest
        - neurodamus-core
        - neurodamus-hippocampus
        - neurodamus-neocortex
        - neurodamus-thalamus
        - neurodamus-mousify
        - parquet-converters
        - py-basalt
        - 'py-mvdtool%gcc'
        - 'py-neurodamus+all_deps'
        - py-pytouchreader
        - reportinglib
        - spatial-index
        - spykfunc
        - steps
        - 'synapsetool%gcc'
        - touchdetector
        - unit-test-translator
      projections:
        all: '{name}/{version}'
        ^coreneuron+knl: '{name}-knl/{version}'
        +common: '{name}/{version}-commonmods'
  packages:
    all:
      compiler: [gcc@9.3.0, intel]
      providers:
        mpi: [hpe-mpi@2.21]
        lapack: [intel-mkl@2019.3.199]
    python:
      version: [3.8.3]
  specs:
    - asciitoh5@1.0
    - functionalizer@3.12.2
    - model-neocortex%intel
    - nest@2.18.0
    - nest@2.20.0
    - neurodamus-core~common%intel
    - neurodamus-core+common
    - neurodamus-hippocampus+coreneuron%intel^coreneuron+caliper
    - neurodamus-hippocampus+coreneuron%intel^coreneuron+caliper+knl
    - neurodamus-mousify+coreneuron%intel^coreneuron+caliper
    - neurodamus-neocortex+coreneuron%intel^coreneuron+caliper
    - neurodamus-neocortex+coreneuron%intel^coreneuron+caliper+knl
    - neurodamus-thalamus+coreneuron%intel^coreneuron+caliper
    - neurodamus-thalamus+coreneuron%intel^coreneuron+caliper+knl
    - parquet-converters
    - py-basalt@0.2.9
    - py-neurodamus+all_deps
    - py-pytouchreader
    - reportinglib%intel
    - spatial-index
    - spykfunc
    - steps+petsc
    - synapsetool
    - touchdetector
    - unit-test-translator
