spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - asciitoh5
        - brainbuilder
        - brayns
        - brayns-brainatlas
        - brayns-topologyviewer
        - brion+python
        - circuit-build
        - circuit-analysis
        - connectome-tools
        - emsim
        - functionalizer
        - gene-expression-volume
        - meshball
        - model-neocortex
        - nest
        - neurodamus-core
        - neurodamus-hippocampus
        - neurodamus-neocortex
        - neurodamus-thalamus
        - neurodamus-mousify
        - parquet-converters
        - placement-algorithm
        - py-region-grower
        - psp-validation
        - py-atlalign
        - py-atlannot
        - py-atlas-building-tools
        - py-atldld
        - py-basalt
        - py-bba-datafetch
        - py-bba-webexporter
        - py-bbp-analysis-framework
        - py-bbp-workflow
        - py-bglibpy
        - py-bluepy
        - py-bluepyefe
        - py-bluepymm
        - py-bluepyopt
        - py-bluepyemodel
        - py-bluepyparallel
        - py-bluepysnap
        - py-currentscape
        - py-data-integrity-check
        - py-efel
        - py-entity-management
        - py-notebook
        - py-minis-validation
        - py-morph-tool
        - py-morphio
        - py-morphology-repair-workflow
        - 'py-mvdtool%gcc'
        - 'py-neurodamus+all_deps'
        - py-nexusforge
        - py-nexus-sdk
        - py-simwriter
        - py-sonata-network-reduction
        - py-token-fetch
        - py-pytouchreader
        - py-visual-cortex-analysis
        - regiodesics
        - reportinglib
        - spatial-index
        - spykfunc
        - 'synapsetool%gcc'
        - steps
        - touchdetector
        - ultraliser
        - unit-test-translator
      projections:
        all: '{name}/{version}'
        ^coreneuron+knl: '{name}-knl/{version}'
        +common: '{name}/{version}-commonmods'
  packages:
    all:
      compiler: [gcc@9.3.0, intel]
      providers:
        mpi: [hpe-mpi@2.21]
        lapack: [intel-mkl@2019.3.199]
    python:
      version: [3.8.3]
  specs:
    - asciitoh5@1.0
    - brainbuilder
    - brayns%gcc +brion ^brion@3.3.1 ^ospray%intel
    - brayns@1.0.1%gcc +brion ^brion@3.1.0 ^ospray%intel
    - brayns-brainatlas@0.1.0%gcc ^brayns@0.8.0 ^ospray@1.7.3%intel
    - brayns-membranelessorganelles@0.1.0%gcc ^brayns@0.8.0 ^ospray@1.7.3%intel
    - brayns@0.8.0%gcc +opendeck +brion ^brion@3.1.0 ^ospray@1.7.3%intel
    - brayns-topologyviewer@0.1.0%gcc ^brayns@0.8.0 ^ospray@1.7.3%intel
    - brion@3.1.0 +python
    - brion@3.2.0 +python
    - brion@3.3.0 +python
    - brion@3.3.1 +python
    - circuit-build
    - connectome-tools
    - emsim
    - functionalizer@3.12.2
    - gene-expression-volume
    - meshball ^brion@3.1.0
    - model-neocortex%intel
    - nest@2.18.0
    - nest@2.20.0
    - neurodamus-core~common%intel
    - neurodamus-core+common
    - neurodamus-hippocampus+coreneuron%intel^coreneuron+caliper
    - neurodamus-hippocampus+coreneuron%intel^coreneuron+caliper+knl
    - neurodamus-mousify+coreneuron%intel^coreneuron+caliper
    - neurodamus-neocortex+coreneuron%intel^coreneuron+caliper
    - neurodamus-neocortex+coreneuron%intel^coreneuron+caliper+knl
    - neurodamus-thalamus+coreneuron%intel^coreneuron+caliper
    - neurodamus-thalamus+coreneuron%intel^coreneuron+caliper+knl
    - parquet-converters
    - placement-algorithm
    - placement-algorithm@2.1.4
    - psp-validation%gcc ^neuron%intel
    - py-atlalign ^py-six@1.15.0
    - py-atlannot
    - py-atlas-building-tools
    - py-atldld
    - py-basalt@0.2.9
    - py-bba-datafetch
    - py-bba-webexporter
    - py-bbp-analysis-framework
    - py-bbp-workflow ^py-h5py~mpi
    - py-bglibpy%gcc ^neuron%intel
    - py-bluepy
    - py-bluepyefe
    - py-bluepymm%gcc ^neuron%intel
    - py-bluepyopt%gcc ^neuron%intel
    - py-bluepyemodel
    - py-bluepyparallel
    - py-bluepysnap
    - py-currentscape
    - py-data-integrity-check
    - py-efel
    - py-entity-management
    - py-minis-validation%gcc ^neuron%intel
    - py-morphio
    - py-morphology-repair-workflow
    - py-morph-tool%gcc ^neuron%intel
    - py-morph-tool@2.8.0%gcc ^neuron%intel
    - py-neurodamus+all_deps
    - py-nexusforge
    - py-nexus-sdk
    - py-notebook
    - py-pytouchreader
    - py-region-grower
    - py-region-grower@0.2.4
    - py-simwriter
    - py-sonata-network-reduction%gcc ^neuron%intel^py-ipython%gcc
    - py-token-fetch
    - py-visual-cortex-analysis ^py-h5py~mpi
    - regiodesics
    - reportinglib%intel
    - spatial-index
    - spykfunc
    - steps+petsc
    - synapsetool
    - touchdetector
    - ultraliser
    - unit-test-translator
